"""add url, text and summary field and embedding model to article table

Revision ID: 0aaa555fe83c
Revises: a6e00d281b7c
Create Date: 2025-05-01 18:22:06.172950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '0aaa555fe83c'
down_revision: Union[str, None] = 'a6e00d281b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('article', sa.Column('url', sa.String(), nullable=False))
    op.add_column('article', sa.Column('text', sa.String(), nullable=False))
    op.add_column('article', sa.Column('summary', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'summary')
    op.drop_column('article', 'text')
    op.drop_column('article', 'url')
    op.drop_table('embedding')
    # ### end Alembic commands ###
