"""Create Article Model

Revision ID: a6e00d281b7c
Revises: 
Create Date: 2025-04-29 14:16:37.118522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e00d281b7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('points', sa.Integer(), nullable=False))
    op.add_column('article', sa.Column('comment_counts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'comment_counts')
    op.drop_column('article', 'points')
    # ### end Alembic commands ###
